package com.fresh.coding.agendaapi.entities;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a student level entity within the application.
 * This class maps to the 'student_level' table in the database.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode
@Entity
@Builder
public class StudentLevel {

    /**
     * The unique identifier for the student level.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the student level.
     */
    private String levelName;

    /**
     * A textual description of the student level.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * A list of users associated with this student level.
     * This relationship is mapped by the 'level' field in the {@link User} entity.
     * The list is initialized to an empty list by default.
     * Cascade type ALL and orphanRemoval are enabled, which means that all changes to the users
     * are cascaded to the database, and orphaned users are removed.
     */
    @Builder.Default
    @ToString.Exclude
    @OneToMany(mappedBy = "level", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<User> users = new ArrayList<>();

    /**
     * The timestamp when the student level was created.
     * Automatically set before persisting the entity.
     */
    private LocalDateTime createdAt;

    /**
     * The timestamp when the student level was last updated.
     * Automatically updated before updating the entity.
     */
    private LocalDateTime updatedAt;

    /**
     * Sets the creation timestamp to the current time if it is not already set.
     * Also sets the updated timestamp to the current time before persisting the entity.
     */
    @PrePersist
    public void beforeCreate() {
        if (createdAt == null) {
            this.createdAt = LocalDateTime.now();
        }
        if (updatedAt == null) {
            this.updatedAt = LocalDateTime.now();
        }
    }

    /**
     * Updates the timestamp to the current time before updating the entity.
     */
    @PreUpdate
    public void beforeUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
